### PR TITLE
Added detection of another Coinhive clone

### PR DESCRIPTION
**Pull request by GramThanos**
I came across an undetected miner on a [site](https://inside-out.xyz/technology/how-dns-tunneling-works.html).

### CODE REVIEW

**Review by Zorono — APPROVED** [review]

**Comment by mandano** [comment]
hey @GramThanos, i just wanted to check out your code addition on that side, i don't seem to find a miner like you are checking for on that site respectively any, it is already a long time ago that you posted this therfore no suprise, do you have a current example by chance, where one can test with? or am i missing it?

**Comment by GramThanos** [comment]
Hey @mandano,

Yes, it seems that the site that I found back then is no longer active.
I did a reverse serach of the key words and found a site that has the miner code in the source, but commented out. You can check this site `https://blogbynoob.blogspot.com` and search for `_siteKey`.

Furthermore, using the `CoinHive.Anonymous` code piece I found on the site above, I can see that there are many sites running related code. Check here: `https://publicwww.com/websites/CoinHive.Anonymous/`.

**Comment by mandano** [comment]
ah yes thx, though the commented out code would be in theory detected by the existing code right? as it is using the full attribute name, will check out the pages from the search engine

**Comment by GramThanos** [comment]
> the commented out code would be in theory detected by the existing code right?

I haven't checked that. Maybe. I remember back then that the variables were quite similar but still the code evade detection.

**Review by xd4rker — APPROVED** [review]

**Pull request merged**
